### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by earrp** [bayeslife/api-add-in#1]
A few questions:
1) We get an error when selecting ExportDiagram in EA: EA_MenuClick: Illegal characters in path
2) I can only build the Debug version, Release gives errors: metadatafiles YamlDotNet.dll and IAGAddIn.dll could not be found and reference assemblies UnitySubset v3.5 not found
3) How to use the generated dll in EA on another machine? Place it in a specific folder or in the GAC?

**Comment by bayeslife** [comment]
1. Have a look at the exportDiagram method in DiagramManager.cs.
It forms the name of the file(s) to export to by composing the diagram.Note and the diagram.Name
into d:\tmp\content.  I think you probably haven't given the diagram any Notes value.
(Unfortunately diagrams dont have anywhere to store such meta data...as do normal elements).
2.  Cant say I've every tried to build a release version.  I'll have to get back to you on this. How important is it to have a release version?
3. See the installation section on the readme.  You just copy the built artefacts onto the host and update the registry.  I have a backlog item to build an installation for the plugin.  Let me know how important ease of installation is to you?

**Comment by CIfemenia** [comment]
According to API1 example, different resource types are defined in static resource-types.raml file.
I need to specify a resource API with both collection-get and item-get functions.
Examples : 
 - /products GET (Collection)
 - /products/{id} GET (Item)

How to modelize it with EA, since it is not possible to define multiple resource types for a single resource?
 - Do I need to define a new combined resource "collection-item-get" ?
 - Do I need to define /product/{id} as a child resource?

Thanks for your help?

**Comment by CIfemenia** [comment]
In the same way, what do you suggest to design under EA a resource with POST and GET methods?
Examples : 
 - /products GET (to get list of resources)
 - /products POST (to create resource)
Do I have to define a new special resource-type in resource-types.raml file?

**Comment by bayeslife** [comment]
Hi,  What I do for this situation is to create a resource for the collection and a separate (possible sub resource) for the item and off each of separate resources is a different Resource Type. There is an example of this in the Example.EAP file.  See diagram called Outbound Simple Message V1606.
I'll attach a picture.
Hope it helps.

**Comment by bayeslife** [comment]
![outbound simple message v1606](https://cloud.githubusercontent.com/assets/19249025/22772501/e5cc4df4-ef01-11e6-9972-5e14bfd73b97.png)

**Comment by bayeslife** [comment]
See there is a resource /v1606/outbound representing the collection of outbound messages and there is a separate /{message-id}.  The former has Resource Type post-one-way, the latter item-get. 
The generated RAML has:

/sms:
  uriParameters: {}
  /v1606/outbound:
    description: Outbound SMS messages resource .
    uriParameters: {}
    /{messageId}:
      description: Entity representing an outbound message
      uriParameters:
        messageId:
          description: An identifier for the message that will be sent or received.
          type: string
          example: ABCD1234
      type:
        item-get:
          infoSchema: infoSchema
          respSchema: SMSMessageResponse
          sample400Resp: !include samples/sample400BadRequest-sample.json
          sample401Resp: !include samples/sample401-Unauthorized-sample.json
          sample403Resp: !include samples/sample403-Forbidden-sample.json
          sample404Resp: !include samples/sample404Resp-sample.json
          sample405Resp: !include samples/sample405-MethodNotAllowed-sample.json
          sample406Resp: !include samples/sample406-NotAcceptable-sample.json
          sample200Resp: !include samples/response-sample.SimpleMessageServiceResponse.json
      get:
        description: To retrieve details of an outgoing  message, make an HTTP GET to the Message URI.
    type:
      item-post-oneway:
        infoSchema: infoSchema
        postInfoSchema: infoSchema
        postReqSchema: smsMessageRequest
        postRespSchema: SMSMessageResponse
        sample400Resp: !include samples/sample400BadRequest-sample.json
        sample401Resp: !include samples/sample401-Unauthorized-sample.json
        sample403Resp: !include samples/sample403-Forbidden-sample.json
        sample405Resp: !include samples/sample405-MethodNotAllowed-sample.json
        sample406Resp: !include samples/sample406-NotAcceptable-sample.json
        postSample200Resp: !include samples/response-sample.SimpleMessageServiceResponse.json
        postSampleReq: !include samples/requestSchema-sample.SimpleMessageServiceRequest.json

**Comment by bayeslife** [comment]
> /sms:
  uriParameters: {}
  /v1606/outbound:
    description: Outbound SMS messages resource .
    uriParameters: {}
    /{messageId}:
      description: Entity representing an outbound message
      uriParameters:
        messageId:
          description: An identifier for the message that will be sent or received.
          type: string
          example: ABCD1234
      type:
        item-get:
          infoSchema: infoSchema
          respSchema: SMSMessageResponse
          sample400Resp: !include samples/sample400BadRequest-sample.json
          sample401Resp: !include samples/sample401-Unauthorized-sample.json
          sample403Resp: !include samples/sample403-Forbidden-sample.json
          sample404Resp: !include samples/sample404Resp-sample.json
          sample405Resp: !include samples/sample405-MethodNotAllowed-sample.json
          sample406Resp: !include samples/sample406-NotAcceptable-sample.json
          sample200Resp: !include samples/response-sample.SimpleMessageServiceResponse.json
      get:
        description: To retrieve details of an outgoing  message, make an HTTP GET to the Message URI.
    type:
      item-post-oneway:
        infoSchema: infoSchema
        postInfoSchema: infoSchema
        postReqSchema: smsMessageRequest
        postRespSchema: SMSMessageResponse
        sample400Resp: !include samples/sample400BadRequest-sample.json
        sample401Resp: !include samples/sample401-Unauthorized-sample.json
        sample403Resp: !include samples/sample403-Forbidden-sample.json
        sample405Resp: !include samples/sample405-MethodNotAllowed-sample.json
        sample406Resp: !include samples/sample406-NotAcceptable-sample.json
        postSample200Resp: !include samples/response-sample.SimpleMessageServiceResponse.json
        postSampleReq: !include samples/requestSchema-sample.SimpleMessageServiceRequest.json

**Comment by bayeslife** [comment]
[api.txt](https://github.com/bayeslife/api-add-in/files/762879/api.txt)
