### ISSUE TITLE
Binary solution

### ISSUE THREAD

**Issue by mikhailsubachev** [bayeslife/api-add-in#12]
Hello guys, the extension looks like exactly what I;m looking for. but unfortunately I do not have Visiual Studion, neither I can use it. coudl you also publish binary files to workaround a step of building the solution

thank you in advance

Mike

**Comment by bayeslife** [comment]
Visual Studio is available as a Community Edition which I use to build it.
Please try this: 
https://www.visualstudio.com/vs/community/

**Comment by mikhailsubachev** [comment]
Hello, I tried to build the solution but I had lots of errors, it seems that interop.ea of EA v.13 is not compatible with the solution.  can you advise how to proceed? 
![image](https://user-images.githubusercontent.com/30725377/29910881-04d4c180-8e2c-11e7-9a50-326e4fac4592.png)

**Comment by bayeslife** [comment]
Hi,  I used EA v.13 and a number of users have reported also they are using v13.
Could you check that you have updated the Interop.EA.dll within the UnitTest project to point to the right dll.
![image](https://user-images.githubusercontent.com/19249025/29913784-47dc8c0c-8e8a-11e7-9962-9111a7d3d101.png)
Rgds, Phil

**Comment by alaif** [comment]
When UnitTest was removed from build we got the APIAddIn built. In my opinion providing people with a binary build (.zip file seems sufficient) would make installation easier.

**Comment by AC75007344** [comment]
I've got the same errors than mikhailsubachev though i'm using EA v12.1. I can't find any solution even while removing the "UnitTestProject". Any advice ? 

![image](https://user-images.githubusercontent.com/38663311/39186987-4e9ec630-47cc-11e8-9091-742d9f2ffa3b.png)

**Comment by AC75007344** [comment]
To be more precise, here is the result when removing the "UnitTestProjet". There are still some errors

Thus the system says it cannot register the generated "D:\api-add-in-master\APIAddIn\APIAddIn\bin\Debug\APIAddIn.dll" and asks to run the application as Administrator (<< access to the HKEY_CLASSES_ROOT\APIAddIn.APIManager is denied >>)

![image](https://user-images.githubusercontent.com/38663311/39187498-cb02fd3a-47cd-11e8-82a5-bdbadbb58ae6.png)

**Comment by bayeslife** [comment]
Hi,
I use the community of edition of Visual Studio to develop this which is
free.  That is all you need.
Rgds,
Phil

**Comment by bayeslife** [comment]
Hi,

Can you check the the Interop EA reference does point to a file installed
by Enterprise Architect.
On my system the reference point so the file C:\Program Files (x86)\Sparx
Systems\EA\Interop.EA.dll



Rgds,
Phil

**Comment by AC75007344** [comment]
Thank you Phil for your answer

The reference path does match exactly the EA file on my system, namely "C:\Program Files (x86)\Sparx Systems\EA\Interop.EA.dll"

![image](https://user-images.githubusercontent.com/38663311/39233668-53e6dd94-4871-11e8-88f2-7032f2b06a3c.png)

![image](https://user-images.githubusercontent.com/38663311/39233962-2d33c062-4872-11e8-9db0-614bdccf0d5c.png)

**Comment by bayeslife** [comment]
Can you build the plugin when running visual studio as the super 
user/admin user?

The issue is that visual studio does not have permission to overwrite 
the dll.

Also ensure the enterprise architect is closed when you build.


Rgds,

Phil

**Comment by AC75007344** [comment]
Je suis absent(e) du bureau jusqu'au 14/05/2018

Je répondrai à votre message dès mon retour.

Si cela ne peut attendre, merci de faire suivre ou de mettre en copie mes
collègues qui répondront à vos demandes.

Pour toute anomalie ou demande d'évolution, merci de créer un dossier CAP
pour transmission au national.


Remarque : ceci est une réponse automatique à votre message  "Re:
[bayeslife/api-add-in] Binary solution (#12)" envoyé le 28/04/2018 3:18:35.


C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
