### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by procfxgen** [bayeslife/api-add-in#13]
The type or namespace name 'SVGExport' could not be found (are you missing a using directive or an assembly reference?)

where could I found SVGExport assembly reference ?

**Comment by bayeslife** [comment]
Have you install the required plugin SVG Export (http://community.sparxsystems.com/community-resources/706-svg-diagram-export-add-in)  please locate this SVGExport.dll in the install.
Cheers, Phil

**Comment by procfxgen** [comment]
I added reference to "C:\Program Files (x86)\Siemens\EA SVG Export\SVGExport.dll"
But 'EAPlugin' does not contain a definition for 'SaveDiagramAsSvg'	in DiagramManager.cs.

**Comment by bayeslife** [comment]
I think you have the wrong version of this plugin.  I think you have installed version 1.04 rather than 1.06.

You can also just comment out that reference as that is simply a convenience menu option to export diagrams as SVG.

**Comment by procfxgen** [comment]
Ok thanks that works !

**Comment by bayeslife** [comment]
Excellent. Good luck
