### ISSUE TITLE
Type or Name Space SVGExport Error

### ISSUE THREAD

**Issue by rksumo23** [bayeslife/api-add-in#7]
When I try to build the solution, I am getting the following error. Could someone help me overcome this.

CS0246 -- The type or namespace name "SVGExport" could not be found (are you missing a using directive or an assemble reference) in APIAddIn

CS0006 -- IAGAddIn.dll could not be found

**Comment by bayeslife** [comment]
Install the SVG Export utility. 
http://community.sparxsystems.com/community-resources/706-svg-diagram-export-add-in

Then update the reference in the project to point to the dll 
(SVGExport.dll).

Then rebuild the project.


The dll now builds as APIAddin.dll rather than IAGAddIn.dll


Rgds,

Phil

**Comment by rksumo23** [comment]
Hi Phil,

Thanks a lot for your response. I tried few more things as mentioned by you, but still not getting the APIMDG extension in Sparx. I am attaching the screenshot for more reference. Could you please have a look and advise. My goal is to have APIMDG extension in Sparx Extensions.

[IssueDesc-APIAddIn.docx](https://github.com/bayeslife/api-add-in/files/955612/IssueDesc-APIAddIn.docx)

Thanks,
Sundar

**Comment by rksumo23** [comment]
Finally I got it. Two mistakes I did was having the APIAddIn Project Folder readonly which caused the issue when building the project. Next is in DLL, I have the path, instead of just the name. Now I got the APIMDG extension listed in Sparx.

**Comment by bayeslife** [comment]
Nice work. Glad you've got it working.  Cheers, Phil
