### ISSUE TITLE
Unable to get Export Schema Option in API MDG Extension

### ISSUE THREAD

**Issue by rksumo23** [bayeslife/api-add-in#8]
Hi,

I am able to build the APIAddIn project and SVGExport option. But once I complete all, when I go to Sparx, I am not getting the Export Schema option from API MDI Extenstion. Attached screenshot for reference on the error. Also the entire step by step procedure which I followed. Could you please advise what could be the issue. I need to generate JSON data from the class diagram. Thanks in advance.

[Error-Screenshot.docx](https://github.com/bayeslife/api-add-in/files/956227/Error-Screenshot.docx)
[InstallStep.docx](https://github.com/bayeslife/api-add-in/files/956229/InstallStep.docx)

Regards,
Sundar

**Comment by Semprini** [comment]
The Stereotype on the diagram needs to be SchemaDiagram which will then show the menu items for JSON export. (Other diagram stereotypes which the add in looks for are APIDiagram and SampleDiagram)
![image](https://cloud.githubusercontent.com/assets/298725/25410839/4df8eb52-2a6d-11e7-9cc9-543968edd4a8.png)

**Comment by rksumo23** [comment]
Hi Paul,

Thanks and will look into this tomorrow. If possible, can we have your
contact number to talk to.

Regards,
Sundar

**Comment by rksumo23** [comment]
This has worked. Thanks a lot for your response.
