### ISSUE TITLE
Getting an error when trying to ExportAPI option

### ISSUE THREAD

**Issue by rksumo23** [bayeslife/api-add-in#9]
We have created a diagram and marked Stereotype as “APIDiagram”.
Right clicked on the layout, selected API MDG -- ExportAPI option to export the API.
When doing so, we end up with the following error.

An error occurred while attempting to communicate with an Addin:
APIAddIn (APIAddIn.APIAddinClass) 
"EA_MenuClick: Can't find matching ID"
Please contact the add-in provider for assistance.

Could you please help. Screenshot attached for reference.

[Error-Screenshot.docx](https://github.com/bayeslife/api-add-in/files/958878/Error-Screenshot.docx)

Thanks,
Sundar

**Comment by bayeslife** [comment]
Hi Sundar,

Attached is the sample EAP file.

Could you try with the diagrams in this file under 'Rest APIs'

Rgds,

Phil

**Comment by samsantiago** [comment]
Hi Phil,
  You're add-in appears quite useful.  I was trying to find the Example.eap file you mention in order to experiment with the add-in.  Would you be able to include that file in this repo?  Or how can we get a copy of it?

Thanks,

Sam

**Comment by bayeslife** [comment]
Hi Sam,

Here is the sample EAP file.

Please see the APIDiagrams under the REST APIs package.

Rgds,

Phil

**Comment by samsantiago** [comment]
Hi Phil,

Thank you for responding.  I am not seeing the attachment.  Am I missing something?

Thanks,

Sam


On May 1, 2017, at 12:50 AM, bayeslife <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Sam,

Here is the sample EAP file.

Please see the APIDiagrams under the REST APIs package.

Rgds,

Phil

**Comment by bayeslife** [comment]
Hi Sam,

Sorry I replied back to github. Please email me directly at 
phil@xceptionale.com.

Cheers,

Phil

**Comment by acalbazana** [comment]
I have the same error when exporting using the plugin.  I'm running EA 13.0 build 1309.  Is this a problem with the version of EA?  The images in the repo suggest an older version is being used.

Thanks!

Alejandro

**Comment by bayeslife** [comment]
Hi, The plugin builds and runs fine in version 13. I originally developed this with version 12 but use it on a daily basis with version 13.
Cheers, Phil

**Comment by bayeslife** [comment]
Those error indicate the that diagram doesnt contain the correct elements.  I can supply the sample eap file which has a couple examples which should help you.
